from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "fabric" / "src" / "client" / "java"

REPLACEMENTS = [
    ("net.minecraft.client.renderer.entity.model.EntityModelLayer", "net.minecraft.client.model.geom.ModelLayerLocation"),
    ("EntityModelLayer", "ModelLayerLocation"),
    ("net.minecraft.client.model.TexturedModelData", "net.minecraft.client.model.geom.builders.LayerDefinition"),
    ("TexturedModelData", "LayerDefinition"),
    ("net.minecraft.client.model.ModelData", "net.minecraft.client.model.geom.builders.MeshDefinition"),
    ("ModelData", "MeshDefinition"),
    ("net.minecraft.client.model.ModelPartData", "net.minecraft.client.model.geom.builders.PartDefinition"),
    ("ModelPartData", "PartDefinition"),
    ("net.minecraft.client.model.ModelPartBuilder", "net.minecraft.client.model.geom.builders.CubeListBuilder"),
    ("ModelPartBuilder", "CubeListBuilder"),
    ("net.minecraft.client.model.ModelTransform", "net.minecraft.client.model.geom.PartPose"),
    ("ModelTransform", "PartPose"),
    ("net.minecraft.client.model.Dilation", "net.minecraft.client.model.geom.builders.CubeDeformation"),
    ("Dilation", "CubeDeformation"),
    ("net.minecraft.client.model.ModelPart", "net.minecraft.client.model.geom.ModelPart"),
    ("net.minecraft.client.renderer.entity.EntityRendererFactory", "net.minecraft.client.renderer.entity.EntityRendererProvider"),
    ("EntityRendererFactory", "EntityRendererProvider"),
    ("net.minecraft.client.renderer.block.entity.BlockEntityRendererFactory", "net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider"),
    ("BlockEntityRendererFactory", "BlockEntityRendererProvider"),
    ("net.minecraft.client.renderer.block.entity.BlockEntityRendererFactories", "net.minecraft.client.renderer.blockentity.BlockEntityRenderers"),
    ("BlockEntityRendererFactories", "BlockEntityRenderers"),
    ("net.minecraft.client.player.ClientPlayerEntity", "net.minecraft.client.player.LocalPlayer"),
    ("ClientPlayerEntity", "LocalPlayer"),
    ("net.minecraft.client.gui.DrawContext", "net.minecraft.client.gui.GuiGraphics"),
    ("DrawContext", "GuiGraphics"),
    ("net.minecraft.client.font.TextRenderer", "net.minecraft.client.gui.Font"),
    ("TextRenderer", "Font"),
    ("net.minecraft.client.math.MatrixStack", "com.mojang.blaze3d.vertex.PoseStack"),
    ("MatrixStack", "PoseStack"),
    ("net.minecraft.client.renderer.entity.model.EntityModelLoader", "net.minecraft.client.model.geom.EntityModelSet"),
    ("EntityModelLoader", "EntityModelSet"),
    ("net.minecraft.client.renderer.entity.model.BipedEntityModel", "net.minecraft.client.model.HumanoidModel"),
    ("BipedEntityModel", "HumanoidModel"),
    ("net.minecraft.client.renderer.model.json.ModelTransformationMode", "net.minecraft.world.item.ItemDisplayContext"),
    ("ModelTransformationMode", "ItemDisplayContext"),
    ("net.minecraft.resource.ResourceType", "net.minecraft.server.packs.PackType"),
    ("net.minecraft.resource.ResourceManager", "net.minecraft.server.packs.resources.ResourceManager"),
    ("net.minecraft.profiler.Profiler", "net.minecraft.util.profiling.ProfilerFiller"),
    ("new net.minecraft.resources.Identifier(\"swgc\",", "Identifier.fromNamespaceAndPath(\"swgc\","),
    (".runDirectory", ".gameDirectory"),
    (".useKey", ".keyUse"),
    ("getEntityModelLoader()", "getEntityModels()"),
    (".yaw", ".yRot"),
    (".pitch", ".xRot"),
    (".roll", ".zRot"),
    ("MobEntityRenderer", "MobRenderer"),
    ("HeldItemFeatureRenderer", "ItemInHandLayer"),
    ("EntityModelLayerRegistry", "ModelLayerRegistry"),
    ("BuiltinItemRendererRegistry", "SwgcItemRendererRegistry"),
    ("HudRenderCallback", "SwgcHudElements"),
    ("PartPoseationMode", "ItemDisplayContext"),
    ("net.minecraft.client.renderer.entity.animation", "net.minecraft.client.animation"),
    ("net.minecraft.client.renderer.VertexConsumerProvider", "net.minecraft.client.renderer.MultiBufferSource"),
    ("VertexConsumerProvider", "MultiBufferSource"),
    ("getModelPart(", "bakeLayer("),
    ("net.minecraft.client.animation.Animation", "che.swgc.client.compat.animation.Animation"),
    ("net.minecraft.client.animation.Transformation", "che.swgc.client.compat.animation.Transformation"),
    ("net.minecraft.client.animation.AnimationHelper", "che.swgc.client.compat.animation.AnimationHelper"),
    ("net.minecraft.client.renderer.entity.model.SinglePartEntityModel", "che.swgc.client.compat.model.SinglePartEntityModel"),
    ("net.minecraft.client.renderer.entity.model.ModelWithArms", "che.swgc.client.compat.model.ModelWithArms"),
    ("net.minecraft.client.renderer.entity.feature", "net.minecraft.client.renderer.entity.layers"),
    ("net.minecraft.client.renderer.entity.model.EntityModel", "net.minecraft.client.model.EntityModel"),
    ("net.minecraft.client.renderer.entity.model.PlayerEntityModel", "net.minecraft.client.model.player.PlayerModel"),
    ("net.minecraft.client.renderer.entity.model.PlayerModel", "net.minecraft.client.model.player.PlayerModel"),
    ("net.minecraft.client.renderer.block.entity", "net.minecraft.client.renderer.blockentity"),
    ("net.minecraft.client.renderer.model.json.ItemDisplayContext", "net.minecraft.world.item.ItemDisplayContext"),
    ("net.minecraft.client.renderer.RenderLayer", "net.minecraft.client.renderer.rendertype.RenderType"),
    ("RenderLayer", "RenderType"),
    ("extends net.minecraft.client.renderer.entity.MobRenderer<", "extends che.swgc.client.render.SwgcMobRenderer<"),
    ("getTextureLocation(", "textureLocation("),
]

for path in ROOT.rglob("*.java"):
    text = path.read_text(encoding="utf-8")
    original = text
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    if text != original:
        path.write_text(text, encoding="utf-8")
        print(f"updated {path.relative_to(ROOT)}")
